name: Update China IP list (Source someip) and generate BypassCN.rule

on:  
  workflow_run:
    workflows: [Update China IP list and generate BypassCN.rule]
    types:
      - completed
jobs:
  build:
    name: Generate BypassCN.rule
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into directory
      uses: actions/checkout@v4
    
    - name: Run the updategeoip-cn-someip.sh
      run: |
        echo "#BypassCNandLan,绕过大陆和局域网someip,1,1,1,0,0,0," >> BypassCNandLan_someip.rules

        curl https://raw.githubusercontent.com/0x2E/someip/build/cidr.txt >> BypassCNandLan_someip.rules

        sed -i '2{/^$/d;}' BypassCNandLan_someip.rules # 删除源文件内第二行的空行
        echo 10.0.0.0/8 >> BypassCNandLan_someip.rules
        echo 172.16.0.0/12 >> BypassCNandLan_someip.rules
        echo 192.168.0.0/16 >> BypassCNandLan_someip.rules
      shell: bash

    - name: Git Add BypassCNandLan_someip.rules
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git fetch
        cp ./BypassCNandLan_someip.rules ./rules/BypassCNandLan_someip.rules
        git add ./rules/BypassCNandLan_someip.rules
        if ! git commit -am "Updated at $(date) (Source: https://github.com/0x2E/someip)"; then
          curl -o BypassCNandLan_someip.rules -L https://github.com/FQrabbit/SSTap-Rule/raw/master/rules/BypassCNandLan_someip.rules         
          hash1=$(sha256sum "./BypassCNandLan_someip.rules" | awk '{print $1}')
          hash2=$(sha256sum "./rules/BypassCNandLan_someip.rules" | awk '{print $1}')
          echo -e "hash1=$hash1\nhash2=$hash2"
          if [ "$hash1" == "$hash2" ]; then
            echo "Hashes match. The files are identical."
            echo "Upstream not updated"
          else
            echo "Hashes do not match. The files are different."
            echo "ERROR! Upstream updated! There's something went WRONG!"
            exit 1
          fi
        fi

            
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true
